version: '3'

services:
  db:
    image: postgres:11.1-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - $DB_PORT:$DB_PORT
  server:
    build: ./server
    container_name: server
    command: ['make', 'dev']
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - ./server:/code
      - ./client/dist:/code/dist
    ports:
      - $PORT:$PORT
      - $DEBUG_PORT:$DEBUG_PORT
    expose:
      - $PORT
      - $DEBUG_PORT
    depends_on:
      - db
  client:
    build: ./client
    container_name: client
    command: ['make', 'dev']
    tty: true
    stdin_open: true
    volumes:
      - ./client:/code
      - client_node_modules:/code/node_modules

volumes:
  pgdata:
    driver: local
  client_node_modules:
    driver: local
